name: SpotifyTrueShuffle

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: windows11-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install Pillow==10.4.0 requests==2.32.3 Flask==3.0.3 ttkthemes==3.2.2 pdoc==13.0.0.
      # ADJUST THIS: build your documentation into docs/.
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: pdoc SpotifyTrueShuffle.pyw FlaskServer.py ApiCredentialsWindow.py AuthenticateWindow.py ShuffleInputPopupBox.py -o /docs --logo https://raw.githubusercontent.com/chasstev/SpotifyTrueShuffle/74b9a4ffce60426a312abbf0711c870ff5388df2/assets/icon.png

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: windows11-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4